### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by sara-kassani** [AdityaGolatkar/Classification-of-Breast-Cancer-Histology-using-Deep-Learning#1]
Would be possible to share weights? (my_best_weights.h5)

**Comment by AdityaGolatkar** [comment]
Here

weight 1 :
https://drive.google.com/open?id=1tMgA2_FFqh5nXyAU_HoMj1bxOIl4n4Fb
weight 2 :
https://drive.google.com/open?id=18FNaIBE7UpZ_sKthrafiO-IvwiLQ_TlA

I have used two weights and then took an average of the results from the
two.

Thank you

**Comment by sara-kassani** [comment]
Awesome, thanks Aditya :)
