### ISSUE TITLE
 Documentation or information regarding the process of training the model

### ISSUE THREAD

**Issue by sirivellamadhu** [AdityaGolatkar/Classification-of-Breast-Cancer-Histology-using-Deep-Learning#2]
Hi Aditya,

I have gone through your project i did not found any documentation of information to train the model and also did not found the best weights in the file "my_net.py".

Could please share the details about training.

Thank you very much.

sincerely,
madhu sirivella

**Comment by AdityaGolatkar** [comment]
I think you can find the details about the training in the paper (section 3.2). I have also provided the code, it's a simple and written in Keras. 
You can find the weights here
weight 1 :
https://drive.google.com/open?id=1tMgA2_FFqh5nXyAU_HoMj1bxOIl4n4Fb
weight 2 :
https://drive.google.com/open?id=18FNaIBE7UpZ_sKthrafiO-IvwiLQ_TlA
I have used two weights and then took an average of the results from the
two.
